import * as cfg from './config';
import {
  generateAllConsistencyLevelsTable,
  generateAllContractsTable,
  generateCctpSupportTabs,
  generateProductSupportTables,
  generateTestnetFaucetsTable,
} from './details';
import { generateGovernanceMainnetTable, generateGovernanceTestnetTable } from './governance';
import { generateQueriesTable } from './generateQueriesTable';
import { indentBlock } from './util';
import { TagManager } from './tagManager';
import { DOCS_SNIPPETS_DIR } from './env';
import { cctpV1Support, cctpV2Support } from './generated';

type ContractModule = 'coreBridge' | 'tokenBridge' | 'relayer' | 'cctp' | 'executor' | 'tokenBridgeRelayer' | 'tokenBridgeRelayerWithReferrer';

async function main() {
  try {
    const [chains, tagManager] = await Promise.all([
      cfg.getDocChains(),
      TagManager.create(DOCS_SNIPPETS_DIR),
    ]);

    const contractTags: Array<{ tag: string; module: ContractModule }> = [
      { tag: 'CORE_ADDRESS', module: 'coreBridge' },
      { tag: 'WTT_ADDRESS', module: 'tokenBridge' },
      { tag: 'RELAYER_BRIDGE_ADDRESS', module: 'relayer' },
    ];

    for (const { tag, module } of contractTags) {
      await tagManager.replace(tag, generateAllContractsTable(chains, module));
    }

    await tagManager.replace(
      'CONSISTENCY_LEVELS',
      generateAllConsistencyLevelsTable(chains)
    );
    await tagManager.replace(
      'TESTNET_FAUCETS',
      generateTestnetFaucetsTable(chains)
    );
    const productTables = generateProductSupportTables(chains);
    for (const [product, table] of Object.entries(productTables)) {
      const tagSuffix = product === 'tokenBridge' ? 'WTT' : product.toUpperCase();
      await tagManager.replace(`SUPPORTED_BLOCKCHAIN_${tagSuffix}`, table);
    }

    await tagManager.replace(
      'SUPPORTED_BLOCKCHAIN_CCTP',
      generateCctpSupportTabs(chains, cctpV1Support, cctpV2Support)
    );

    const queriesTable = await generateQueriesTable(chains);
    await tagManager.replace('SUPPORTED_QUERIES', queriesTable);

    const govMainnetTable = await generateGovernanceMainnetTable(chains);
    const govTestnetTable = await generateGovernanceTestnetTable(chains);
    await tagManager.replace(
      'GOVERNANCE_MAINNET',
      indentBlock(govMainnetTable, 4)
    );
    await tagManager.replace(
      'GOVERNANCE_TESTNET',
      indentBlock(govTestnetTable, 4)
    );

    const written = await tagManager.commit();
    const modifications = tagManager.getModifications();

    if (written.length === 0) {
      console.log('All autogenerated snippets already up to date.');
    } else {
      console.log(`Updated ${written.length} snippet file(s).`);
      for (const [tag, files] of Object.entries(modifications)) {
        console.log(`  ${tag}: ${files.length} file(s)`);
      }
    }
  } catch (err) {
    console.error(err);
    process.exitCode = 1;
  }
}

void main();
