name: CheckMkDocsBuild
on:
  # Trigger the workflow on a new pull request on main
  pull_request_target:
    branches:
      - main

jobs:
  build-docs-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Allow to move dotfiles
        run: |
          # move also dotfile with *
          shopt -s dotglob

      - name: Clone Wormhole MKDocs
        run: |
          # clone mkdocs repo locally
          git clone https://${{ secrets.REPO_SCOPED_TOKEN }}@github.com/papermoonio/wormhole-mkdocs.git

      - name: Update wormhole-docs content in the mkdocs-repository
        run: |
          # update the wormhole-docs submodule
          # running this command on the branch associated with the PR will test the workflow using the latest commits
          git submodule update --remote

      - name: Install pip requirements
        run: |
          cd wormhole-mkdocs
          # Upgrade pip and setuptools
          pip3 install --upgrade pip setuptools==65.7.0
          # Install testresources first to satisfy launchpadlib dependency
          pip3 install testresources
          # Now install the rest of the dependencies
          pip3 install -r requirements.txt && echo "Dependencies installed successfully" || echo "Error while installing dependencies"
          
      - name: Build mkdocs
        run: |
          cd wormhole-mkdocs
          # change destination build folder in mkdocs YAML to local site/
          sed -i 's/site_dir.*/site_dir: site/' mkdocs.yml
          # build project
          python3 -m mkdocs build
