# This CI workflow was adapted from (and inspired by) [PaperMoon](https://papermoon.io/)’s MkDocs workflows previously used for Wormhole Docs. 
# Original reference implementation: https://github.com/papermoonio/workflows/blob/main/.github/workflows/core-pr-mkdocs-build.yml

name: PR Docs Build

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Install pip requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Build Docs
        run: mkdocs build --strict
